export type Animal = {
  id: string;
  photo: string;
  tagId: string;
  species: "Cattle" | "Goat" | "Sheep" | "Poultry";
  breed: string;
  age: number;
  farm: string;
  location: string;
  temperature: string;
  heartRate: string;
  healthStatus: "Healthy" | "Watch" | "Diseased" | "Recovering";
  vaccinationStatus: "Current" | "Due Soon" | "Overdue";
  gpsPosition: string;
  lastCheckup: string;
  aiHealthScore: number;
  feedingSchedule: string;
  breedingStatus: string;
  weight: string;
  medicalHistory: string;
};

export const livestockStats = [
  { label: "Livestock Overview", value: "18,420", helper: "registered animals" },
  { label: "Health Monitoring", value: "94.3%", helper: "healthy population" },
  { label: "Vaccination Records", value: "1,248", helper: "due in 30 days" },
  { label: "Disease Detection", value: "37", helper: "AI flagged cases" },
  { label: "GPS Tracking", value: "12,906", helper: "active collars" },
  { label: "AI Health Score", value: "91/100", helper: "fleet average" },
];

export const animals: Animal[] = [
  {
    id: "1",
    photo: "/livestock/cow.svg",
    tagId: "AGX-C-1048",
    species: "Cattle",
    breed: "Holstein Friesian",
    age: 4,
    farm: "Greenridge Dairy",
    location: "Barn A - Pen 12",
    temperature: "38.4 C",
    heartRate: "68 bpm",
    healthStatus: "Healthy",
    vaccinationStatus: "Current",
    gpsPosition: "6.5244, 3.3792",
    lastCheckup: "Today, 08:15",
    aiHealthScore: 96,
    feedingSchedule: "06:00, 13:00, 19:00",
    breedingStatus: "Open",
    weight: "612 kg",
    medicalHistory: "Routine mineral supplement completed on Jul 9.",
  },
  {
    id: "2",
    photo: "/livestock/goat.svg",
    tagId: "AGX-G-2217",
    species: "Goat",
    breed: "Boer",
    age: 2,
    farm: "Savanna Ridge",
    location: "Goat Unit 3",
    temperature: "39.7 C",
    heartRate: "92 bpm",
    healthStatus: "Watch",
    vaccinationStatus: "Due Soon",
    gpsPosition: "7.3775, 3.9470",
    lastCheckup: "Today, 07:40",
    aiHealthScore: 78,
    feedingSchedule: "07:00, 16:30",
    breedingStatus: "Pregnancy check due",
    weight: "67 kg",
    medicalHistory: "Elevated cough frequency detected over 18 hours.",
  },
  {
    id: "3",
    photo: "/livestock/sheep.svg",
    tagId: "AGX-S-0872",
    species: "Sheep",
    breed: "Dorper",
    age: 3,
    farm: "Riverbend Farm",
    location: "Pasture West",
    temperature: "39.1 C",
    heartRate: "82 bpm",
    healthStatus: "Recovering",
    vaccinationStatus: "Current",
    gpsPosition: "8.4966, 4.5421",
    lastCheckup: "Yesterday, 16:20",
    aiHealthScore: 84,
    feedingSchedule: "Grazing rotation plus 18:00 supplement",
    breedingStatus: "Bred, day 46",
    weight: "74 kg",
    medicalHistory: "Hoof treatment completed; gait improving.",
  },
  {
    id: "4",
    photo: "/livestock/poultry.svg",
    tagId: "AGX-P-5314",
    species: "Poultry",
    breed: "Layer Hybrid",
    age: 1,
    farm: "East Poultry Estate",
    location: "House 4",
    temperature: "41.2 C",
    heartRate: "284 bpm",
    healthStatus: "Healthy",
    vaccinationStatus: "Current",
    gpsPosition: "6.6018, 3.3515",
    lastCheckup: "Today, 09:05",
    aiHealthScore: 93,
    feedingSchedule: "Automated feed line every 4 hours",
    breedingStatus: "Layer production group",
    weight: "1.9 kg",
    medicalHistory: "No abnormal mortality trend in current cycle.",
  },
  {
    id: "5",
    photo: "/livestock/cow.svg",
    tagId: "AGX-C-1192",
    species: "Cattle",
    breed: "Jersey",
    age: 5,
    farm: "Greenridge Dairy",
    location: "Barn B - Pen 6",
    temperature: "40.1 C",
    heartRate: "86 bpm",
    healthStatus: "Diseased",
    vaccinationStatus: "Overdue",
    gpsPosition: "6.5250, 3.3820",
    lastCheckup: "Today, 06:55",
    aiHealthScore: 61,
    feedingSchedule: "Reduced ration with hydration support",
    breedingStatus: "Do not breed",
    weight: "488 kg",
    medicalHistory: "Mastitis protocol started; vet review scheduled.",
  },
  {
    id: "6",
    photo: "/livestock/goat.svg",
    tagId: "AGX-G-2364",
    species: "Goat",
    breed: "Kalahari Red",
    age: 1,
    farm: "Savanna Ridge",
    location: "Nursery Yard",
    temperature: "39.0 C",
    heartRate: "88 bpm",
    healthStatus: "Healthy",
    vaccinationStatus: "Current",
    gpsPosition: "7.3780, 3.9491",
    lastCheckup: "Jul 17, 14:30",
    aiHealthScore: 94,
    feedingSchedule: "07:30, 15:30, mineral block",
    breedingStatus: "Juvenile",
    weight: "34 kg",
    medicalHistory: "Weaning completed with stable weight gain.",
  },
  {
    id: "7",
    photo: "/livestock/sheep.svg",
    tagId: "AGX-S-0955",
    species: "Sheep",
    breed: "West African Dwarf",
    age: 6,
    farm: "Riverbend Farm",
    location: "Pasture South",
    temperature: "38.8 C",
    heartRate: "76 bpm",
    healthStatus: "Healthy",
    vaccinationStatus: "Due Soon",
    gpsPosition: "8.4982, 4.5409",
    lastCheckup: "Jul 16, 10:10",
    aiHealthScore: 89,
    feedingSchedule: "Rotational grazing, evening hay",
    breedingStatus: "Retired breeder",
    weight: "69 kg",
    medicalHistory: "Annual parasite screening due next week.",
  },
  {
    id: "8",
    photo: "/livestock/poultry.svg",
    tagId: "AGX-P-5488",
    species: "Poultry",
    breed: "Broiler",
    age: 1,
    farm: "East Poultry Estate",
    location: "House 2",
    temperature: "42.0 C",
    heartRate: "302 bpm",
    healthStatus: "Watch",
    vaccinationStatus: "Current",
    gpsPosition: "6.6022, 3.3528",
    lastCheckup: "Today, 05:45",
    aiHealthScore: 73,
    feedingSchedule: "High-protein ration every 3 hours",
    breedingStatus: "Meat production group",
    weight: "2.4 kg",
    medicalHistory: "Heat stress risk rising after ventilation alert.",
  },
];

export const livestockTabs = [
  "Animal List",
  "Health Monitoring",
  "Vaccination Records",
  "Disease Detection",
  "GPS Tracking",
  "Feeding Schedule",
  "Breeding Records",
  "Weight Monitoring",
  "Medical History",
];
